---
- name: Copy cfg files to server
  copy:
      dest: "{{ srcds_server_path }}/tf" 
      src: cfg
      force: yes
      owner: "{{ srcds_username }}"
- name: Copy addons files to server
  copy:
    dest: "{{ srcds_server_path }}/tf"
    src: addons 
    force: yes
    owner: "{{ srcds_username }}"

- name: Copy mapcycle
  copy:
    dest: "{{ srcds_server_path }}/tf/mapcycle.txt"
    src: mapcycle.txt
    force: yes
    owner: "{{ srcds_username }}"