---
- name: install Python utility packages
  become: true
  apt:
    name:
      - python3
      - python3-pip
  when: aws_access_key_id is defined


- name: Install s3_bucket python dependencies
  become: true
  command: pip3 install boto boto3 botocore
  when: aws_access_key_id is defined

- name: Get list of maps from FastDL (S3 Bucket)
  aws_s3:
    mode: list
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    bucket: "{{ aws_storage_bucket_name }}"
    prefix: "tf/maps/"
    marker: "tf/maps/"
  register: s3_bucket_items
  when: aws_access_key_id is defined

- name: Download all maps to the server
  aws_s3:
    mode: get
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    bucket: "{{ aws_storage_bucket_name }}"
    object: "{{ item }}"
    dest: "{{ srcds_server_path }}/tf/maps/{{ item|basename }}"
  with_items: "{{ s3_bucket_items.s3_keys }}"
  when: aws_access_key_id is defined

- name: Install unzip packages
  apt:
    name: 
      - bzip2
      - unzip
    state: present
  when: aws_access_key_id is defined

- name: Unzip all maps
  command: "bzip2 -d -f {{ srcds_server_path }}/tf/maps/{{ item|basename}}"
  with_items: "{{ s3_bucket_items.s3_keys }}"
  when: s3_bucket_items is defined