# Create the tf2 service 
---
- name: Copy run_server script
  template:
    src: service/run_server.sh
    dest: "{{ srcds_server_path }}/run_server.sh"
    owner: "{{srcds_username}}"

- name: Copy tf script
  template:
    src: service/tf.sh
    dest: "{{ srcds_server_path }}/tf.sh"
    owner: "{{srcds_username}}"

- name: Copy tf2_ds script
  template:
    src: service/tf2_ds.txt
    dest: "{{ srcds_server_path }}/tf2_ds.txt"
    owner: "{{srcds_username}}"

- name: Create systemctl service
  template:
    src: service/tf-server.service
    dest: /etc/systemd/system/tf-server.service

- name: Make scripts executable
  command: "chmod +x {{ srcds_server_path }}/run_server.sh"

- name: Make scripts executable
  command: "chmod +x {{ srcds_server_path }}/tf.sh"

- name: Enable systemctl service
  command: systemctl enable tf-server.service

- name: Start systemctl service
  command: systemctl start tf-server.service