---
- hosts: all
  become: true
  connection: local
  tasks:
    - include_role:
        name: base
    - include_role:
        name: tf2_server
    - include_role:
        name: tf2_server_competitive
    - name: Reboot server
      reboot:
          reboot_timeout: 600
          msg: Reboot initiated by Ansible
          